/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AccountUsageStatisticsInterval.
* @enum {}
* @readonly
*/
export default class AccountUsageStatisticsInterval {
    
        /**
         * value: "1h"
         * @const
         */
        "1h" = "1h";

    
        /**
         * value: "1d"
         * @const
         */
        "1d" = "1d";

    

    /**
    * Returns a <code>AccountUsageStatisticsInterval</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AccountUsageStatisticsInterval} The enum <code>AccountUsageStatisticsInterval</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

