/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiUsageDataTransfer from './ApiUsageDataTransfer';

/**
 * The ApiUsageEntry model module.
 * @module model/ApiUsageEntry
 * @version 3.1.0
 */
class ApiUsageEntry {
    /**
     * Constructs a new <code>ApiUsageEntry</code>.
     * Usage history entry
     * @alias module:model/ApiUsageEntry
     * @param requests {Number} 
     * @param data {module:model/ApiUsageDataTransfer} 
     */
    constructor(requests, data) { 
        
        ApiUsageEntry.initialize(this, requests, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, requests, data) { 
        obj['requests'] = requests;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>ApiUsageEntry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiUsageEntry} obj Optional instance to populate.
     * @return {module:model/ApiUsageEntry} The populated <code>ApiUsageEntry</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiUsageEntry();

            if (data.hasOwnProperty('requests')) {
                obj['requests'] = ApiClient.convertToType(data['requests'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiUsageDataTransfer.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiUsageEntry</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiUsageEntry</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiUsageEntry.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          ApiUsageDataTransfer.validateJSON(data['data']);
        }

        return true;
    }


}

ApiUsageEntry.RequiredProperties = ["requests", "data"];

/**
 * @member {Number} requests
 */
ApiUsageEntry.prototype['requests'] = undefined;

/**
 * @member {module:model/ApiUsageDataTransfer} data
 */
ApiUsageEntry.prototype['data'] = undefined;






export default ApiUsageEntry;

