/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class CommodityType.
* @enum {}
* @readonly
*/
export default class CommodityType {
    
        /**
         * value: "agricultural"
         * @const
         */
        "agricultural" = "agricultural";

    
        /**
         * value: "energy"
         * @const
         */
        "energy" = "energy";

    
        /**
         * value: "metal"
         * @const
         */
        "metal" = "metal";

    
        /**
         * value: "all"
         * @const
         */
        "all" = "all";

    

    /**
    * Returns a <code>CommodityType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/CommodityType} The enum <code>CommodityType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

