/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Country.
* @enum {}
* @readonly
*/
export default class Country {
    
        /**
         * value: "fr"
         * @const
         */
        "fr" = "fr";

    
        /**
         * value: "us"
         * @const
         */
        "us" = "us";

    
        /**
         * value: "de"
         * @const
         */
        "de" = "de";

    
        /**
         * value: "nz"
         * @const
         */
        "nz" = "nz";

    
        /**
         * value: "nl"
         * @const
         */
        "nl" = "nl";

    
        /**
         * value: "uk"
         * @const
         */
        "uk" = "uk";

    
        /**
         * value: "es"
         * @const
         */
        "es" = "es";

    
        /**
         * value: "cn"
         * @const
         */
        "cn" = "cn";

    
        /**
         * value: "ch"
         * @const
         */
        "ch" = "ch";

    
        /**
         * value: "gr"
         * @const
         */
        "gr" = "gr";

    
        /**
         * value: "be"
         * @const
         */
        "be" = "be";

    
        /**
         * value: "pt"
         * @const
         */
        "pt" = "pt";

    
        /**
         * value: "it"
         * @const
         */
        "it" = "it";

    
        /**
         * value: "all"
         * @const
         */
        "all" = "all";

    

    /**
    * Returns a <code>Country</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Country} The enum <code>Country</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

