/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CryptoExchangeItem model module.
 * @module model/CryptoExchangeItem
 * @version 3.1.0
 */
class CryptoExchangeItem {
    /**
     * Constructs a new <code>CryptoExchangeItem</code>.
     * A cryptocurrency exchange
     * @alias module:model/CryptoExchangeItem
     * @param id {String} Exchange identifier
     * @param name {String} Exchange name
     * @param yearEstablished {Number} Exchange established year
     */
    constructor(id, name, yearEstablished) { 
        
        CryptoExchangeItem.initialize(this, id, name, yearEstablished);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, yearEstablished) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['year_established'] = yearEstablished;
    }

    /**
     * Constructs a <code>CryptoExchangeItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CryptoExchangeItem} obj Optional instance to populate.
     * @return {module:model/CryptoExchangeItem} The populated <code>CryptoExchangeItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CryptoExchangeItem();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('year_established')) {
                obj['year_established'] = ApiClient.convertToType(data['year_established'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CryptoExchangeItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CryptoExchangeItem</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CryptoExchangeItem.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

CryptoExchangeItem.RequiredProperties = ["id", "name", "year_established"];

/**
 * Exchange identifier
 * @member {String} id
 */
CryptoExchangeItem.prototype['id'] = undefined;

/**
 * Exchange name
 * @member {String} name
 */
CryptoExchangeItem.prototype['name'] = undefined;

/**
 * Exchange established year
 * @member {Number} year_established
 */
CryptoExchangeItem.prototype['year_established'] = undefined;






export default CryptoExchangeItem;

