/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CryptoExchangeItem from './CryptoExchangeItem';

/**
 * The CryptoExchangesList model module.
 * @module model/CryptoExchangesList
 * @version 3.1.0
 */
class CryptoExchangesList {
    /**
     * Constructs a new <code>CryptoExchangesList</code>.
     * A list of cryptocurrency exchanges
     * @alias module:model/CryptoExchangesList
     * @param items {Array.<module:model/CryptoExchangeItem>} 
     */
    constructor(items) { 
        
        CryptoExchangesList.initialize(this, items);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, items) { 
        obj['items'] = items;
    }

    /**
     * Constructs a <code>CryptoExchangesList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CryptoExchangesList} obj Optional instance to populate.
     * @return {module:model/CryptoExchangesList} The populated <code>CryptoExchangesList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CryptoExchangesList();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [CryptoExchangeItem]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CryptoExchangesList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CryptoExchangesList</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CryptoExchangesList.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                CryptoExchangeItem.validateJSON(item);
            };
        }

        return true;
    }


}

CryptoExchangesList.RequiredProperties = ["items"];

/**
 * @member {Array.<module:model/CryptoExchangeItem>} items
 */
CryptoExchangesList.prototype['items'] = undefined;






export default CryptoExchangesList;

