/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConversionInfo from './ConversionInfo';
import CryptoConversionQuery from './CryptoConversionQuery';

/**
 * The CryptoConversion model module.
 * @module model/CryptoConversion
 * @version 3.1.0
 */
class CryptoConversion {
    /**
     * Constructs a new <code>CryptoConversion</code>.
     * @alias module:model/CryptoConversion
     * @param info {module:model/ConversionInfo} 
     * @param query {module:model/CryptoConversionQuery} 
     * @param result {Number} 
     */
    constructor(info, query, result) { 
        
        CryptoConversion.initialize(this, info, query, result);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, info, query, result) { 
        obj['info'] = info;
        obj['query'] = query;
        obj['result'] = result;
    }

    /**
     * Constructs a <code>CryptoConversion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CryptoConversion} obj Optional instance to populate.
     * @return {module:model/CryptoConversion} The populated <code>CryptoConversion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CryptoConversion();

            if (data.hasOwnProperty('info')) {
                obj['info'] = ConversionInfo.constructFromObject(data['info']);
            }
            if (data.hasOwnProperty('query')) {
                obj['query'] = CryptoConversionQuery.constructFromObject(data['query']);
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CryptoConversion</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CryptoConversion</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CryptoConversion.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `info`
        if (data['info']) { // data not null
          ConversionInfo.validateJSON(data['info']);
        }
        // validate the optional field `query`
        if (data['query']) { // data not null
          CryptoConversionQuery.validateJSON(data['query']);
        }

        return true;
    }


}

CryptoConversion.RequiredProperties = ["info", "query", "result"];

/**
 * @member {module:model/ConversionInfo} info
 */
CryptoConversion.prototype['info'] = undefined;

/**
 * @member {module:model/CryptoConversionQuery} query
 */
CryptoConversion.prototype['query'] = undefined;

/**
 * @member {Number} result
 */
CryptoConversion.prototype['result'] = undefined;






export default CryptoConversion;

