/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorDetails from './ErrorDetails';

/**
 * The ErrorResponseBody model module.
 * @module model/ErrorResponseBody
 * @version 3.1.0
 */
class ErrorResponseBody {
    /**
     * Constructs a new <code>ErrorResponseBody</code>.
     * @alias module:model/ErrorResponseBody
     * @param error {module:model/ErrorDetails} 
     */
    constructor(error) { 
        
        ErrorResponseBody.initialize(this, error);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, error) { 
        obj['error'] = error;
    }

    /**
     * Constructs a <code>ErrorResponseBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ErrorResponseBody} obj Optional instance to populate.
     * @return {module:model/ErrorResponseBody} The populated <code>ErrorResponseBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorResponseBody();

            if (data.hasOwnProperty('error')) {
                obj['error'] = ErrorDetails.constructFromObject(data['error']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ErrorResponseBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ErrorResponseBody</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ErrorResponseBody.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `error`
        if (data['error']) { // data not null
          ErrorDetails.validateJSON(data['error']);
        }

        return true;
    }


}

ErrorResponseBody.RequiredProperties = ["error"];

/**
 * @member {module:model/ErrorDetails} error
 */
ErrorResponseBody.prototype['error'] = undefined;






export default ErrorResponseBody;

