/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LastQuote model module.
 * @module model/LastQuote
 * @version 3.1.0
 */
class LastQuote {
    /**
     * Constructs a new <code>LastQuote</code>.
     * @alias module:model/LastQuote
     * @param symbol {String} Symbol name
     * @param ask {Number} The ask price.
     * @param bid {Number} The bid price.
     * @param mid {Number} The mid price.
     * @param timestamp {Number} 
     */
    constructor(symbol, ask, bid, mid, timestamp) { 
        
        LastQuote.initialize(this, symbol, ask, bid, mid, timestamp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, symbol, ask, bid, mid, timestamp) { 
        obj['symbol'] = symbol;
        obj['ask'] = ask;
        obj['bid'] = bid;
        obj['mid'] = mid;
        obj['timestamp'] = timestamp;
    }

    /**
     * Constructs a <code>LastQuote</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LastQuote} obj Optional instance to populate.
     * @return {module:model/LastQuote} The populated <code>LastQuote</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LastQuote();

            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('ask')) {
                obj['ask'] = ApiClient.convertToType(data['ask'], 'Number');
            }
            if (data.hasOwnProperty('bid')) {
                obj['bid'] = ApiClient.convertToType(data['bid'], 'Number');
            }
            if (data.hasOwnProperty('mid')) {
                obj['mid'] = ApiClient.convertToType(data['mid'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LastQuote</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LastQuote</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LastQuote.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['symbol'] && !(typeof data['symbol'] === 'string' || data['symbol'] instanceof String)) {
            throw new Error("Expected the field `symbol` to be a primitive type in the JSON string but got " + data['symbol']);
        }

        return true;
    }


}

LastQuote.RequiredProperties = ["symbol", "ask", "bid", "mid", "timestamp"];

/**
 * Symbol name
 * @member {String} symbol
 */
LastQuote.prototype['symbol'] = undefined;

/**
 * The ask price.
 * @member {Number} ask
 */
LastQuote.prototype['ask'] = undefined;

/**
 * The bid price.
 * @member {Number} bid
 */
LastQuote.prototype['bid'] = undefined;

/**
 * The mid price.
 * @member {Number} mid
 */
LastQuote.prototype['mid'] = undefined;

/**
 * @member {Number} timestamp
 */
LastQuote.prototype['timestamp'] = undefined;






export default LastQuote;

