/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class SymbolsListMode.
* @enum {}
* @readonly
*/
export default class SymbolsListMode {
    
        /**
         * value: "full"
         * @const
         */
        "full" = "full";

    
        /**
         * value: "base"
         * @const
         */
        "base" = "base";

    

    /**
    * Returns a <code>SymbolsListMode</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/SymbolsListMode} The enum <code>SymbolsListMode</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

