/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Tradewatch);
  }
}(this, function(expect, Tradewatch) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Tradewatch.CryptoExchangeItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CryptoExchangeItem', function() {
    it('should create an instance of CryptoExchangeItem', function() {
      // uncomment below and update the code to test CryptoExchangeItem
      //var instance = new Tradewatch.CryptoExchangeItem();
      //expect(instance).to.be.a(Tradewatch.CryptoExchangeItem);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Tradewatch.CryptoExchangeItem();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Tradewatch.CryptoExchangeItem();
      //expect(instance).to.be();
    });

    it('should have the property yearEstablished (base name: "year_established")', function() {
      // uncomment below and update the code to test the property yearEstablished
      //var instance = new Tradewatch.CryptoExchangeItem();
      //expect(instance).to.be();
    });

  });

}));
