/**
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Tradewatch);
  }
}(this, function(expect, Tradewatch) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Tradewatch.CursorPageTCustomizedSymbolsOutFull();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CursorPageTCustomizedSymbolsOutFull', function() {
    it('should create an instance of CursorPageTCustomizedSymbolsOutFull', function() {
      // uncomment below and update the code to test CursorPageTCustomizedSymbolsOutFull
      //var instance = new Tradewatch.CursorPageTCustomizedSymbolsOutFull();
      //expect(instance).to.be.a(Tradewatch.CursorPageTCustomizedSymbolsOutFull);
    });

    it('should have the property items (base name: "items")', function() {
      // uncomment below and update the code to test the property items
      //var instance = new Tradewatch.CursorPageTCustomizedSymbolsOutFull();
      //expect(instance).to.be();
    });

    it('should have the property total (base name: "total")', function() {
      // uncomment below and update the code to test the property total
      //var instance = new Tradewatch.CursorPageTCustomizedSymbolsOutFull();
      //expect(instance).to.be();
    });

    it('should have the property currentPage (base name: "current_page")', function() {
      // uncomment below and update the code to test the property currentPage
      //var instance = new Tradewatch.CursorPageTCustomizedSymbolsOutFull();
      //expect(instance).to.be();
    });

    it('should have the property currentPageBackwards (base name: "current_page_backwards")', function() {
      // uncomment below and update the code to test the property currentPageBackwards
      //var instance = new Tradewatch.CursorPageTCustomizedSymbolsOutFull();
      //expect(instance).to.be();
    });

    it('should have the property previousPage (base name: "previous_page")', function() {
      // uncomment below and update the code to test the property previousPage
      //var instance = new Tradewatch.CursorPageTCustomizedSymbolsOutFull();
      //expect(instance).to.be();
    });

    it('should have the property nextPage (base name: "next_page")', function() {
      // uncomment below and update the code to test the property nextPage
      //var instance = new Tradewatch.CursorPageTCustomizedSymbolsOutFull();
      //expect(instance).to.be();
    });

  });

}));
